import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/menu"; // Import your Navbar component

// Load fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar should be outside of the content */}
        <Navbar />

        <div className="content mt-14">
          {children}
        </div>
      </body>
    </html>
  );
}
